apiVersion: apps/v1 # Versi API
kind: StatefulSet # Jenis Objek Kubernetes
metadata:
  name: mongo-statefulset
  namespace: karsajobs-ns # Nama Namespace
  labels:
    app: mongodb
spec:
  serviceName: "mongo-service"
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:3 # Image dari Docker Hub untuk Mongo DB versi 3
        imagePullPolicy: IfNotPresent
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-persistent-storage # Persistent Volume dengan mount path /data/db
          mountPath: /data/db
        - name: mongo-config # ConfigMap dengan mount path /config
          mountPath: /config
        - name: mongo-secret # Secret dengan mount path /etc/mongo-credentials
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-config
        configMap:
          name: mongo-config
          items: 
            - key: mongo.conf
              path: mongo.conf
      - name: mongo-secret
        secret:
          secretName: mongo-secret