apiVersion: v1 # Versi API
kind: PersistentVolume # Jenis Objek Kubernetes
metadata:
  name: mongo-pv-pvc
  namespace: karsajobs-ns # Nama Namespace
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /data/db

---
apiVersion: v1 # Versi API
kind: PersistentVolumeClaim # Jenis Objek Kubernetes
metadata:
  name: mongo-pv-claim
  namespace: karsajobs-ns # Nama Namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi