apiVersion: v1 # Versi API
kind: Secret # Jenis Objek Kubernetes
metadata:
  name: mongo-secret
  namespace: karsajobs-ns # Nama Namespace
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # admin
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # supersecretpassword base64