apiVersion: v1 # Versi API
kind: Service # Jenis Objek Kubernetes
metadata:
  name: karsajobs-ui-service # Nama Service
  namespace: karsajobs-ns # Nama Namespace
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80 # Port expose
  type: NodePort